### ISSUE TITLE
A Couple of Notes

### ISSUE THREAD

**Issue by xof88** [tatyanaberdan/finalproject2#11]
Hi Tat'yana! Really great work on your personal site! Visually it is super nice. I have a couple notes for you to take or leave as you wish:)

1. On your Home page, what about adding a little more detail about what the site is and what it's for? A short description. 
2. Your pages are very pretty and clean. I esp. like the Book Review page. Would be nice to add a picture of each book cover to the post. 
3. One Hundred Years of Solitude is one of my favorites. Enjoy!

Best of luck!
Jane

**Comment by tatyanaberdan** [comment]
Thank you for your feedback - I've added photos and a description! 

And I'm really looking forward to 100 years!!
