### ISSUE TITLE
Maybe add more photos? 

### ISSUE THREAD

**Issue by savvylee11** [tatyanaberdan/finalproject2#2]
You have a very pretty site! I wonder if you can do stylized photos of the books you're reading to add some more visual interest for the reviews. 

Your header photo is especially good, so maybe having photos of the book covers your reading in a style like that could make the site look like a cohesive and welcoming design. 

I really enjoyed the customizations you added, like showing what you're currently reading. Overall, awesome job!

**Comment by tatyanaberdan** [comment]
Thank you for your feedback! I've taken your suggestion and added more photos to liven up my blog post entries!
